"""empty message

Revision ID: a9f3e77861e8
Revises: 
Create Date: 2022-12-13 11:15:20.780843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f3e77861e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_id', sa.String(), nullable=True),
    sa.Column('reservation_no', sa.String(), nullable=True),
    sa.Column('arrival', sa.String(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('reservation_comment', sa.String(), nullable=True),
    sa.Column('reservation_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_id', sa.String(), nullable=True),
    sa.Column('leading_guest', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('guest_surname', sa.String(), nullable=True),
    sa.Column('guest_email', sa.String(), nullable=True),
    sa.Column('guest_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reg_id'], ['registration.reg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_id', sa.String(), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('is_signature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reg_id'], ['registration.reg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_table('guests')
    op.drop_table('registration')
    # ### end Alembic commands ###
